dist: xenial   # required for Python >= 3.7
language: python
python:
  - "3.7"
 
install:
   - pip3 install --upgrade pip
   - pip install coveralls
   - pip install pytest
   - pip install stripe
   - pip install selenium
   - npm install lcov-parse
   - wget -N http://chromedriver.storage.googleapis.com/72.0.3626.7/chromedriver_linux64.zip -P ~/
   - unzip ~/chromedriver_linux64.zip -d ~/
   - rm ~/chromedriver_linux64.zip
   - sudo mv -f ~/chromedriver /usr/local/share/
   - sudo chmod +x /usr/local/share/chromedriver
   - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
   - python -m http.server 8000 &

addons: # get google-chrome-stable
  chrome: stable
script: 
 pytest test.py -v --tb=short

after_success:
 - coveralls
notifications:
  webhooks:
    - /api/v1/challenge/check_builds/
